# Generated by Django 4.1.4 on 2023-02-04 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_category_subscriber"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category", old_name="subscriber", new_name="subscribers",
        ),
    ]
